sonar.projectKey=nl-portal_nl-portal-frontend-libraries
sonar.organization=nl-portal

sonar.sources=packages
sonar.exclusions=packages/app/**

sonar.tests=packages
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx
sonar.test.exclusions=packages/app/**

sonar.javascript.lcov.reportPaths=\
  packages/api/coverage/lcov.info,\
  packages/authentication/coverage/lcov.info,\
  packages/localization/coverage/lcov.info,\
  packages/user-interface/coverage/lcov.info

sonar.sourceEncoding=UTF-8
