sonar.projectKey=nl-portal_nl-portal-frontend-libraries
sonar.organization=nl-portal

sonar.sources=packages/api/src,packages/authentication/src,packages/localization/src,packages/user-interface/src

sonar.javascript.lcov.reportPaths=\
  packages/api/coverage/lcov.info,\
  packages/authentication/coverage/lcov.info,\
  packages/localization/coverage/lcov.info,\
  packages/user-interface/coverage/lcov.info

sonar.exclusions=**/generated/**,**/node_modules/**
sonar.coverage.exclusions=**/generated/**,**/node_modules/**

sonar.sourceEncoding=UTF-8
