interface Config {
  KEYCLOAK_URL?: string;
  KEYCLOAK_REALM?: string;
  KEYCLOAK_CLIENT_ID?: string;
  KEYCLOAK_REDIRECT_URI?: string;
  GRAPHQL_URI?: string;
  REST_URI?: string;
  OPEN_FORMS_SDK_URL?: string;
  OPEN_FORMS_BASE_URL?: string;
  OPEN_FORMS_FORM_ID?: string;
  OPEN_FORMS_ENTRY_ENV?: string;
  OPEN_FORMS_STYLES_URL?: string;
  SHOW_INHABITANT_AMOUNT?: string;
  SHOW_ADDRESS_RESEARCH?: string;
  ADDRESS_RESEARCH_URL?: string;
  ACCOUNT_SHOW_NOTIFICATION_SUBSECTION?: string;
  OVERVIEW_SHOW_INTRO?: string;
  OVERVIEW_SHOW_FORMS_LINK?: string;
  OVERVIEW_SHOW_MAINTENANCE_ALERT?: string;
  OVERVIEW_SHOW_CURRENT_CASES_PREVIEW?: string;
  OVERVIEW_CURRENT_CASES_PREVIEW_LENGTH?: string;
  THEME_CLASS?: string;
}

export const config: Config = {
  KEYCLOAK_URL: window.KEYCLOAK_URL,
  KEYCLOAK_REALM: window.KEYCLOAK_REALM,
  KEYCLOAK_CLIENT_ID: window.KEYCLOAK_CLIENT_ID,
  KEYCLOAK_REDIRECT_URI: window.KEYCLOAK_REDIRECT_URI,
  GRAPHQL_URI: window.GRAPHQL_URI,
  REST_URI: window.REST_URI,
  OPEN_FORMS_BASE_URL: window.OPEN_FORMS_BASE_URL,
  OPEN_FORMS_FORM_ID: window.OPEN_FORMS_FORM_ID,
  OPEN_FORMS_ENTRY_ENV: window.OPEN_FORMS_ENTRY_ENV,
  OPEN_FORMS_SDK_URL: window.OPEN_FORMS_SDK_URL,
  OPEN_FORMS_STYLES_URL: window.OPEN_FORMS_STYLES_URL,
  SHOW_INHABITANT_AMOUNT: window.SHOW_INHABITANT_AMOUNT,
  SHOW_ADDRESS_RESEARCH: window.SHOW_ADDRESS_RESEARCH,
  ADDRESS_RESEARCH_URL: window.ADDRESS_RESEARCH_URL,
  ACCOUNT_SHOW_NOTIFICATION_SUBSECTION: window.ACCOUNT_SHOW_NOTIFICATION_SUBSECTION,
  OVERVIEW_SHOW_INTRO: window.OVERVIEW_SHOW_INTRO,
  OVERVIEW_SHOW_FORMS_LINK: window.OVERVIEW_SHOW_FORMS_LINK,
  OVERVIEW_SHOW_MAINTENANCE_ALERT: window.OVERVIEW_SHOW_MAINTENANCE_ALERT,
  OVERVIEW_SHOW_CURRENT_CASES_PREVIEW: window.OVERVIEW_SHOW_CURRENT_CASES_PREVIEW,
  OVERVIEW_CURRENT_CASES_PREVIEW_LENGTH: window.OVERVIEW_CURRENT_CASES_PREVIEW_LENGTH,
  THEME_CLASS: window.THEME_CLASS,
};
