export const config = {
  OIDC_URL: window.OIDC_URL,
  OIDC_REALM: window.OIDC_REALM,
  OIDC_CLIENT_ID: window.OIDC_CLIENT_ID,
  OIDC_REDIRECT_URI: window.OIDC_REDIRECT_URI,
  OIDC_POST_LOGOUT_REDIRECT_URI: window.OIDC_POST_LOGOUT_REDIRECT_URI,
  GRAPHQL_URI: window.GRAPHQL_URI,
  REST_URI: window.REST_URI,
  SHOW_INHABITANT_AMOUNT: window.SHOW_INHABITANT_AMOUNT,
  ADDRESS_RESEARCH_URL: window.ADDRESS_RESEARCH_URL,
  REPORT_CHANGE_OF_ADDRESS_URL: window.REPORT_CHANGE_OF_ADDRESS_URL,
  CHANGE_IN_USE_OF_SURNAME_URL: window.CHANGE_IN_USE_OF_SURNAME_URL,
  CHANGE_REGISTERED_GENDER_URL: window.CHANGE_REGISTERED_GENDER_URL,
  ADDRESS_RESEARCH_MORE_INFO_URL: window.ADDRESS_RESEARCH_MORE_INFO_URL,
  REQUEST_FOR_CHANGE_BRP_INFO_URL: window.REQUEST_FOR_CHANGE_BRP_INFO_URL,
  REQUEST_CONFIDENTIALITY_OF_DATA_URL:
    window.REQUEST_CONFIDENTIALITY_OF_DATA_URL,
  ACCOUNT_SHOW_NOTIFICATION_SUBSECTION:
    window.ACCOUNT_SHOW_NOTIFICATION_SUBSECTION,
  OVERVIEW_SHOW_INTRO: window.OVERVIEW_SHOW_INTRO,
  OVERVIEW_SHOW_MAINTENANCE_ALERT: window.OVERVIEW_SHOW_MAINTENANCE_ALERT,
  OVERVIEW_SHOW_CURRENT_CASES_PREVIEW:
    window.OVERVIEW_SHOW_CURRENT_CASES_PREVIEW,
  OVERVIEW_CURRENT_CASES_PREVIEW_LENGTH:
    window.OVERVIEW_CURRENT_CASES_PREVIEW_LENGTH,
  THEME_CLASS: window.THEME_CLASS,
  MESSAGE_COUNT_POLLING_INTERVAL: window.MESSAGE_COUNT_POLLING_INTERVAL,
  CASES_PARTIAL_SEARCH: window.CASES_PARTIAL_SEARCH,
  OPEN_KLANT_VERSION: window.OPEN_KLANT_VERSION,
  OGONE_DIRECT_PAYMENT: window.OGONE_DIRECT_PAYMENT,
};
