export const config = {
  OIDC_URL: window.OIDC_URL,
  OIDC_REALM: window.OIDC_REALM,
  OIDC_CLIENT_ID: window.OIDC_CLIENT_ID,
  OIDC_REDIRECT_URI: window.OIDC_REDIRECT_URI,
  GRAPHQL_URI: window.GRAPHQL_URI,
  REST_URI: window.REST_URI,
  SHOW_INHABITANT_AMOUNT: window.SHOW_INHABITANT_AMOUNT,
  SHOW_ADDRESS_RESEARCH: window.SHOW_ADDRESS_RESEARCH,
  ADDRESS_RESEARCH_URL: window.ADDRESS_RESEARCH_URL,
  ACCOUNT_SHOW_NOTIFICATION_SUBSECTION:
    window.ACCOUNT_SHOW_NOTIFICATION_SUBSECTION,
  OVERVIEW_SHOW_INTRO: window.OVERVIEW_SHOW_INTRO,
  OVERVIEW_SHOW_MAINTENANCE_ALERT: window.OVERVIEW_SHOW_MAINTENANCE_ALERT,
  OVERVIEW_SHOW_CURRENT_CASES_PREVIEW:
    window.OVERVIEW_SHOW_CURRENT_CASES_PREVIEW,
  OVERVIEW_CURRENT_CASES_PREVIEW_LENGTH:
    window.OVERVIEW_CURRENT_CASES_PREVIEW_LENGTH,
  THEME_CLASS: window.THEME_CLASS,
  MESSAGE_COUNT_POLLING_INTERVAL: window.MESSAGE_COUNT_POLLING_INTERVAL,
};
