name: Validate Build
on:
    workflow_call:
    pull_request:
        branches:
            - "next-minor"
            - "next-major"
            - "rc/*"
            - "release/*"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
    cancel-in-progress: true
env:
    NODE_VERSION: "20.x"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up Node.js ${{ env.NODE_VERSION }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ env.NODE_VERSION }}
            -   name: Install
                run: npm install -g pnpm@10 && pnpm install
            -   name: Build
                run: pnpm build
            -   name: Test
                run: pnpm test
