name: Validate Build
on:
  push:
    branches:
      - "next-minor"
      - "next-major"
  pull_request:
    branches:
      - "next-minor"
      - "next-major"
      - "release/*"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
env:
  NODE_VERSION: "18.x"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install
        run: npm install -g pnpm && pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test